// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/GenesisEducationKyiv/main-project-delveper/internal/subscription"
	"sync"
)

// Ensure, that EmailSenderMock does implement subscription.EmailSender.
// If this is not the case, regenerate this file with moq.
var _ subscription.EmailSender = &EmailSenderMock{}

// EmailSenderMock is a mock implementation of subscription.EmailSender.
//
//	func TestSomethingThatUsesEmailSender(t *testing.T) {
//
//		// make and configure a mocked subscription.EmailSender
//		mockedEmailSender := &EmailSenderMock{
//			SendFunc: func(email subscription.Email, f float64) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedEmailSender in code that requires subscription.EmailSender
//		// and then make assertions.
//
//	}
type EmailSenderMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(email subscription.Email, f float64) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Email is the email argument value.
			Email subscription.Email
			// F is the f argument value.
			F float64
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *EmailSenderMock) Send(email subscription.Email, f float64) error {
	if mock.SendFunc == nil {
		panic("EmailSenderMock.SendFunc: method is nil but EmailSender.Send was just called")
	}
	callInfo := struct {
		Email subscription.Email
		F     float64
	}{
		Email: email,
		F:     f,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(email, f)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedEmailSender.SendCalls())
func (mock *EmailSenderMock) SendCalls() []struct {
	Email subscription.Email
	F     float64
} {
	var calls []struct {
		Email subscription.Email
		F     float64
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
