// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/GenesisEducationKyiv/main-project-delveper/internal/subscription"
	"sync"
)

// Ensure, that RateGetterMock does implement subscription.RateGetter.
// If this is not the case, regenerate this file with moq.
var _ subscription.RateGetter = &RateGetterMock{}

// RateGetterMock is a mock implementation of subscription.RateGetter.
//
//	func TestSomethingThatUsesRateGetter(t *testing.T) {
//
//		// make and configure a mocked subscription.RateGetter
//		mockedRateGetter := &RateGetterMock{
//			GetFunc: func(ctx context.Context) (float64, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedRateGetter in code that requires subscription.RateGetter
//		// and then make assertions.
//
//	}
type RateGetterMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context) (float64, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *RateGetterMock) Get(ctx context.Context) (float64, error) {
	if mock.GetFunc == nil {
		panic("RateGetterMock.GetFunc: method is nil but RateGetter.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRateGetter.GetCalls())
func (mock *RateGetterMock) GetCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
