// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package rate

import (
	"sync"
)

// Ensure, that GetterMock does implement Getter.
// If this is not the case, regenerate this file with moq.
var _ Getter = &GetterMock{}

// GetterMock is a mock implementation of Getter.
//
//	func TestSomethingThatUsesGetter(t *testing.T) {
//
//		// make and configure a mocked Getter
//		mockedGetter := &GetterMock{
//			GetFunc: func() (float64, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedGetter in code that requires Getter
//		// and then make assertions.
//
//	}
type GetterMock struct {
	// GetFunc mocks the Get method.
	GetFunc func() (float64, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *GetterMock) Get() (float64, error) {
	if mock.GetFunc == nil {
		panic("GetterMock.GetFunc: method is nil but Getter.Get was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc()
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedGetter.GetCalls())
func (mock *GetterMock) GetCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
